# coding:utf-8
__author__ = 'xxj'

import sys
import time
import math
import os
from rediscluster import StrictRedisCluster
import json
import re
import Queue
import lxml.etree
from requests.exceptions import ConnectionError, ConnectTimeout, ReadTimeout
from bs4 import BeautifulSoup
import requests
from excute_js import excu_js

reload(sys)
sys.setdefaultencoding('utf-8')
headers = {
        'accept': 'application/json, text/javascript, */*; q=0.01',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'zh-CN,zh;q=0.9',
        'cache-control': 'no-cache',
        'cookie': 'wanplus_token=36119a190d033d01b3703134f1eca2f2; wanplus_csrf=_csrf_tk_1512233019;',
        # 'cookie': 'UM_distinctid=166e2bc0954625-0f2756a4c40391-594c2a16-144000-166e2bc0955335; wp_pvid=6822851968; wanplus_token=36119a190d033d01b3703134f1eca2f2; wanplus_storage=lf4m67eka3o; wanplus_sid=98261dfe32cdac3a19bf00b9314cf212; wanplus_csrf=_csrf_tk_1512233019; wp_info=ssid=s9720033955; isShown=1; Hm_lvt_f69cb5ec253c6012b2aa449fb925c1c2=1555386424; CNZZDATA1275078652=1757417873-1541401658-https%253A%252F%252Fwww.baidu.com%252F%7C1555564215; gameType=7; Hm_lpvt_f69cb5ec253c6012b2aa449fb925c1c2=1555568871',
        'pragma': 'no-cache',
        # 'referer': 'https://www.wanplus.com/lol/ranking',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
        'x-csrf-token': '1529010235',
        'x-requested-with': 'XMLHttpRequest'
    }

headers1 = {
        'accept': 'application/json, text/javascript, */*; q=0.01',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'zh-CN,zh;q=0.9',
        'cache-control': 'no-cache',
        'cookie': 'wanplus_token=36119a190d033d01b3703134f1eca2f2; wanplus_csrf=_csrf_tk_1512233019; gameType={};',
        # 'cookie': 'cookie: UM_distinctid=166e2bc0954625-0f2756a4c40391-594c2a16-144000-166e2bc0955335; wp_pvid=6822851968; wanplus_token=36119a190d033d01b3703134f1eca2f2; wanplus_storage=lf4m67eka3o; wanplus_sid=98261dfe32cdac3a19bf00b9314cf212; wanplus_csrf=_csrf_tk_1512233019; wp_info=ssid=s9720033955; isShown=1; Hm_lvt_f69cb5ec253c6012b2aa449fb925c1c2=1555386424; CNZZDATA1275078652=1757417873-1541401658-https%253A%252F%252Fwww.baidu.com%252F%7C1555569615; gameType=8; Hm_lpvt_f69cb5ec253c6012b2aa449fb925c1c2=1555573609',
        # 'cookie': 'UM_distinctid=166e2bc0954625-0f2756a4c40391-594c2a16-144000-166e2bc0955335; wp_pvid=6822851968; wanplus_token=36119a190d033d01b3703134f1eca2f2; wanplus_storage=lf4m67eka3o; wanplus_sid=98261dfe32cdac3a19bf00b9314cf212; wanplus_csrf=_csrf_tk_1512233019; wp_info=ssid=s9720033955; isShown=1; Hm_lvt_f69cb5ec253c6012b2aa449fb925c1c2=1555386424; CNZZDATA1275078652=1757417873-1541401658-https%253A%252F%252Fwww.baidu.com%252F%7C1555564215; gameType=7; Hm_lpvt_f69cb5ec253c6012b2aa449fb925c1c2=1555568871',
        'pragma': 'no-cache',
        # 'referer': 'https://www.wanplus.com/lol/ranking',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
        'x-csrf-token': '1529010235',
        'x-requested-with': 'XMLHttpRequest'
    }

# lol
lol = {
    '_gtk': '1529010235',
    'draw': '1',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'teamname',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'kda',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'true',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'killsPergame',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'deathsPergame',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'damagetoheroPermin',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'fstbloodpercentage',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'avgDuration',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'goldpermatch',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'goldsPermin',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'lasthitPermin',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'dragonkillsPergame',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'dragonkillspercentage',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'baronkillsPergame',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'baronkillspercentage',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'wardsplacedpermin',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'wardskilledpermin',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'columns[17][data]': 'wardskilledrate',
    'columns[17][name]': '',
    'columns[17][searchable]': 'true',
    'columns[17][orderable]': 'true',
    'columns[17][search][value]': '',
    'columns[17][search][regex]': 'false',
    'columns[18][data]': 'towertakensPergame',
    'columns[18][name]': '',
    'columns[18][searchable]': 'true',
    'columns[18][orderable]': 'true',
    'columns[18][search][value]': '',
    'columns[18][search][regex]': 'false',
    'columns[19][data]': 'towerdeathsPergame',
    'columns[19][name]': '',
    'columns[19][searchable]': 'true',
    'columns[19][orderable]': 'true',
    'columns[19][search][value]': '',
    'columns[19][search][regex]': 'false',
    'order[0][column]': '2',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '758',
    'type': 'team',
    'gametype': '2',
    'filter': '{"team":{},"player":{},"meta":{}}',
    }

lol1 = {
    '_gtk': '1529010235',
    'draw': '2',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'playername',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'teamname',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'false',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'meta',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'false',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'appearedTimes',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'kda',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'attendrate',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'killsPergame',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'mostkills',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'deathsPergame',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'mostdeaths',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'assistsPergame',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'mostassists',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'goldsPermin',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'lasthitPermin',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'damagetoheroPermin',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'damagetoheroPercent',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'columns[17][data]': 'damagetakenPermin',
    'columns[17][name]': '',
    'columns[17][searchable]': 'true',
    'columns[17][orderable]': 'true',
    'columns[17][search][value]': '',
    'columns[17][search][regex]': 'false',
    'columns[18][data]': 'damagetakenPercent',
    'columns[18][name]': '',
    'columns[18][searchable]': 'true',
    'columns[18][orderable]': 'true',
    'columns[18][search][value]': '',
    'columns[18][search][regex]': 'false',
    'columns[19][data]': 'wardsplacedPermin',
    'columns[19][name]': '',
    'columns[19][searchable]': 'true',
    'columns[19][orderable]': 'true',
    'columns[19][search][value]': '',
    'columns[19][search][regex]': 'false',
    'columns[20][data]': 'wardskilledPermin',
    'columns[20][name]': '',
    'columns[20][searchable]': 'true',
    'columns[20][orderable]': 'true',
    'columns[20][search][value]': '',
    'columns[20][search][regex]': 'false',
    'order[0][column]': '4',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '759',
    'type': 'player',
    'gametype': '2',
    'filter': '{"team":{},"player":{},"meta":{}}'
    }

# 王者荣耀
wzry = {
    '_gtk': '1529010235',
    'draw': '1',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'teamname',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'kda',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'true',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'killsPergame',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'assistsPergame',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'deathsPergame',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'goldpermatch',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'goldsPermin',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'winAvgDuration',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'loseAvgDuration',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'firstbloodrate',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'baronkillsPergame',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'dragonkillsPergame',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'baronkillspercentage',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'dragonkillspercentage',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'totalMinionsKilledPergame',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'totalTowerTaken',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'columns[17][data]': 'totalTowerDeath',
    'columns[17][name]': '',
    'columns[17][searchable]': 'true',
    'columns[17][orderable]': 'true',
    'columns[17][search][value]': '',
    'columns[17][search][regex]': 'false',
    'columns[18][data]': 'towertakensPergame',
    'columns[18][name]': '',
    'columns[18][searchable]': 'true',
    'columns[18][orderable]': 'true',
    'columns[18][search][value]': '',
    'columns[18][search][regex]': 'false',
    'order[0][column]': '2',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '704',
    'type': 'team',
    'gametype': '6',
    'filter': '{"team":{},"player":{},"meta":{}}',
}

wzry1 = {
    '_gtk': '1529010235',
    'draw': '1',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'playername',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'teamname',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'false',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'kda',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'attendrate',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'killsPergame',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'mostkills',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'deathsPergame',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'mostdeaths',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'assistsPergame',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'mostassists',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'damagetoheroPercent',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'damagetakenPercent',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'goldsPercent',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'damagetoheroPermin',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'damagetakenPermin',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'goldsPermin',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'order[0][column]': '3',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '704',
    'type': 'player',
    'gametype': '6',
    'filter': '{"team":{},"player":{},"meta":{}}',
}

# DOTA2
dota = {
    '_gtk': '1529010235',
    'draw': '1',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'teamname',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'appearedTimes',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'true',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'kda',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'winrate',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'killsPergame',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'deathsPergame',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'assistsPergame',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'avgDuration',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'damagetoheroPergame',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'damagetoheroPermin',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'goldsPergame',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'goldsPermin',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'lasthitPergame',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'lasthitPermin',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'deniesPergame',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'experiencePergame',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'columns[17][data]': 'experiencePermin',
    'columns[17][name]': '',
    'columns[17][searchable]': 'true',
    'columns[17][orderable]': 'true',
    'columns[17][search][value]': '',
    'columns[17][search][regex]': 'false',
    'columns[18][data]': 'towertakensPergame',
    'columns[18][name]': '',
    'columns[18][searchable]': 'true',
    'columns[18][orderable]': 'true',
    'columns[18][search][value]': '',
    'columns[18][search][regex]': 'false',
    'columns[19][data]': 'towerdeathsPergame',
    'columns[19][name]': '',
    'columns[19][searchable]': 'true',
    'columns[19][orderable]': 'true',
    'columns[19][search][value]': '',
    'columns[19][search][regex]': 'false',
    'order[0][column]': '2',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '763',
    'type': 'team',
    'gametype': '1',
    'filter': '{"team":{},"player":{},"meta":{}}',
}

dota1 = {
    '_gtk': '1529010235',
    'draw': '1',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'playername',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'teamname',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'false',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'appearedTimes',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'kda',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'attendrate',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'killsPergame',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'mostkills',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'deathsPergame',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'mostdeaths',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'assistsPergame',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'mostassists',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'goldsPermin',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'lasthitPermin',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'damagetoheroPermin',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'damagetoheroPercent',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'experiencePermin',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'columns[17][data]': 'experiencePercent',
    'columns[17][name]': '',
    'columns[17][searchable]': 'true',
    'columns[17][orderable]': 'true',
    'columns[17][search][value]': '',
    'columns[17][search][regex]': 'false',
    'columns[18][data]': 'healingPergame',
    'columns[18][name]': '',
    'columns[18][searchable]': 'true',
    'columns[18][orderable]': 'true',
    'columns[18][search][value]': '',
    'columns[18][search][regex]': 'false',
    'columns[19][data]': 'deniesPergame',
    'columns[19][name]': '',
    'columns[19][searchable]': 'true',
    'columns[19][orderable]': 'true',
    'columns[19][search][value]': '',
    'columns[19][search][regex]': 'false',
    'order[0][column]': '3',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '763',
    'type': 'player',
    'gametype': '1',
    'filter': '{"team":{},"player":{},"meta":{}}'
}

# 球球大作战
qiuqiu = {
    '_gtk': '1529010235',
    'draw': '1',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'teamname',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'matchnum',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'true',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'mvpnum',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'nodeathsnum',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'volume',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'swallow',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'thorns',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'deaths',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'totalscore',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'totalvolume',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'maxvolume',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'totalswallow',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'maxswallow',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'totalthorns',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'maxthorns',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'totaldeaths',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'columns[17][data]': 'maxdeaths',
    'columns[17][name]': '',
    'columns[17][searchable]': 'true',
    'columns[17][orderable]': 'true',
    'columns[17][search][value]': '',
    'columns[17][search][regex]': 'false',
    'order[0][column]': '2',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '497',
    'type': 'team',
    'gametype': '7',
    'filter': '{"team":{},"player":{},"meta":{}}'
}

# 使命召唤OL
smzh_ol = {
        '_gtk': '1529010235',
        'draw': '1',
        'columns[0][data]': 'order',
        'columns[0][name]': '',
        'columns[0][searchable]': 'true',
        'columns[0][orderable]': 'false',
        'columns[0][search][value]': '',
        'columns[0][search][regex]': 'false',
        'columns[1][data]': 'teamname',
        'columns[1][name]': '',
        'columns[1][searchable]': 'true',
        'columns[1][orderable]': 'false',
        'columns[1][search][value]': '',
        'columns[1][search][regex]': 'false',
        'columns[2][data]': 'matchnum',
        'columns[2][name]': '',
        'columns[2][searchable]': 'true',
        'columns[2][orderable]': 'true',
        'columns[2][search][value]': '',
        'columns[2][search][regex]': 'false',
        'columns[3][data]': 'winrate',
        'columns[3][name]': '',
        'columns[3][searchable]': 'true',
        'columns[3][orderable]': 'true',
        'columns[3][search][value]': '',
        'columns[3][search][regex]': 'false',
        'columns[4][data]': 'kpm',
        'columns[4][name]': '',
        'columns[4][searchable]': 'true',
        'columns[4][orderable]': 'true',
        'columns[4][search][value]': '',
        'columns[4][search][regex]': 'false',
        'columns[5][data]': 'dpm',
        'columns[5][name]': '',
        'columns[5][searchable]': 'true',
        'columns[5][orderable]': 'true',
        'columns[5][search][value]': '',
        'columns[5][search][regex]': 'false',
        'columns[6][data]': 'apm',
        'columns[6][name]': '',
        'columns[6][searchable]': 'true',
        'columns[6][orderable]': 'true',
        'columns[6][search][value]': '',
        'columns[6][search][regex]': 'false',
        'columns[7][data]': 'kdr',
        'columns[7][name]': '',
        'columns[7][searchable]': 'true',
        'columns[7][orderable]': 'true',
        'columns[7][search][value]': '',
        'columns[7][search][regex]': 'false',
        'columns[8][data]': 'kills',
        'columns[8][name]': '',
        'columns[8][searchable]': 'true',
        'columns[8][orderable]': 'true',
        'columns[8][search][value]': '',
        'columns[8][search][regex]': 'false',
        'columns[9][data]': 'deaths',
        'columns[9][name]': '',
        'columns[9][searchable]': 'true',
        'columns[9][orderable]': 'true',
        'columns[9][search][value]': '',
        'columns[9][search][regex]': 'false',
        'columns[10][data]': 'assists',
        'columns[10][name]': '',
        'columns[10][searchable]': 'true',
        'columns[10][orderable]': 'true',
        'columns[10][search][value]': '',
        'columns[10][search][regex]': 'false',
        'order[0][column]': '2',
        'order[0][dir]': 'desc',
        'start': '0',
        'length': '1000',
        'search[value]': '',
        'search[regex]': 'false',
        'area': '',
        'eid': '607',
        'type': 'team',
        'gametype': '8',
        'filter': '{"team":{},"player":{},"meta":{}}'
    }

smzh_ol1 = {
    '_gtk': '1529010235',
    'draw': '2',
    'columns[0][data]': 'order',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'playername',
    'columns[1][name]': '',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'false',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'teamname',
    'columns[2][name]': '',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'false',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'matchnum',
    'columns[3][name]': '',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'winrate',
    'columns[4][name]': '',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'kpm',
    'columns[5][name]': '',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'dpm',
    'columns[6][name]': '',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'apm',
    'columns[7][name]': '',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'kdr',
    'columns[8][name]': '',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'hitrate',
    'columns[9][name]': '',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'kills',
    'columns[10][name]': '',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'deaths',
    'columns[11][name]': '',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'assists',
    'columns[12][name]': '',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'fivek',
    'columns[13][name]': '',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'mk',
    'columns[14][name]': '',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'target',
    'columns[15][name]': '',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'mvp',
    'columns[16][name]': '',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'order[0][column]': '10',
    'order[0][dir]': 'desc',
    'start': '0',
    'length': '1000',
    'search[value]': '',
    'search[regex]': 'false',
    'area': '',
    'eid': '607',
    'type': 'player',
    'gametype': '8',
    'filter': '{"team":{},"player":{},"meta":{}}'
}


def get(url, headers, count, des, proxies=None):
    for i in xrange(count):
        response = r1(url, headers, i, des, proxies)
        if response is None:    # 异常
            pass
        elif response.status_code != 200:
            pass
        elif response.status_code == 200:
            return response
    return None


def r1(url, headers, i, des, proxies):
    try:
        print time.strftime('[%Y-%m-%d %H:%M:%S]'), des, url, 'count：', i
        response = requests.get(url=url, headers=headers, timeout=10, verify=False, proxies=proxies)
    except BaseException as e:
        print time.strftime('[%Y-%m-%d %H:%M:%S]'), 'BaseException', 'url：', url, 'message：', e
        response = None
        time.sleep(2)
    return response


def wanplus_all_eid(fileout):
    '''
    获取每一项游戏类别对应的所有赛事
    :return:
    '''
    game_type = {
        '英雄联盟': '2',
        '王者荣耀': '6',
        'DOTA2': '1',
        '球球大作战': '7',
        '使命召唤OL': '8'
    }  # 游戏数据库
    cookie = headers1.get('cookie')
    for game_name, type_name in game_type.items():
        print '游戏名称：', game_name
        print '游戏类型：', type_name
        headers1['cookie'] = cookie.format(type_name)
        # print 'headers：', headers1

        url = 'https://www.wanplus.com/ajax/stats/list'
        data = {
            # '_gtk': '1529010235',
            'draw': '1',
            'columns[0][data]': 'order',
            'columns[0][name]': '',
            'columns[0][searchable]': 'true',
            'columns[0][orderable]': 'false',
            'columns[0][search][value]': '',
            'columns[0][search][regex]': 'false',
            'columns[1][data]': 'teamname',
            'columns[1][name]': '',
            'columns[1][searchable]': 'true',
            'columns[1][orderable]': 'false',
            'columns[1][search][value]': '',
            'columns[1][search][regex]': 'false',
            'columns[2][data]': 'kda',
            'columns[2][name]': '',
            'columns[2][searchable]': 'true',
            'columns[2][orderable]': 'true',
            'columns[2][search][value]': '',
            'columns[2][search][regex]': 'false',
            'columns[3][data]': 'killsPergame',
            'columns[3][name]': '',
            'columns[3][searchable]': 'true',
            'columns[3][orderable]': 'true',
            'columns[3][search][value]': '',
            'columns[3][search][regex]': 'false',
            'columns[4][data]': 'deathsPergame',
            'columns[4][name]': '',
            'columns[4][searchable]': 'true',
            'columns[4][orderable]': 'true',
            'columns[4][search][value]': '',
            'columns[4][search][regex]': 'false',
            'columns[5][data]': 'damagetoheroPermin',
            'columns[5][name]': '',
            'columns[5][searchable]': 'true',
            'columns[5][orderable]': 'true',
            'columns[5][search][value]': '',
            'columns[5][search][regex]': 'false',
            'columns[6][data]': 'fstbloodpercentage',
            'columns[6][name]': '',
            'columns[6][searchable]': 'true',
            'columns[6][orderable]': 'true',
            'columns[6][search][value]': '',
            'columns[6][search][regex]': 'false',
            'columns[7][data]': 'avgDuration',
            'columns[7][name]': '',
            'columns[7][searchable]': 'true',
            'columns[7][orderable]': 'true',
            'columns[7][search][value]': '',
            'columns[7][search][regex]': 'false',
            'columns[8][data]': 'goldpermatch',
            'columns[8][name]': '',
            'columns[8][searchable]': 'true',
            'columns[8][orderable]': 'true',
            'columns[8][search][value]': '',
            'columns[8][search][regex]': 'false',
            'columns[9][data]': 'goldsPermin',
            'columns[9][name]': '',
            'columns[9][searchable]': 'true',
            'columns[9][orderable]': 'true',
            'columns[9][search][value]': '',
            'columns[9][search][regex]': 'false',
            'columns[10][data]': 'lasthitPermin',
            'columns[10][name]': '',
            'columns[10][searchable]': 'true',
            'columns[10][orderable]': 'true',
            'columns[10][search][value]': '',
            'columns[10][search][regex]': 'false',
            'columns[11][data]': 'dragonkillsPergame',
            'columns[11][name]': '',
            'columns[11][searchable]': 'true',
            'columns[11][orderable]': 'true',
            'columns[11][search][value]': '',
            'columns[11][search][regex]': 'false',
            'columns[12][data]': 'dragonkillspercentage',
            'columns[12][name]': '',
            'columns[12][searchable]': 'true',
            'columns[12][orderable]': 'true',
            'columns[12][search][value]': '',
            'columns[12][search][regex]': 'false',
            'columns[13][data]': 'baronkillsPergame',
            'columns[13][name]': '',
            'columns[13][searchable]': 'true',
            'columns[13][orderable]': 'true',
            'columns[13][search][value]': '',
            'columns[13][search][regex]': 'false',
            'columns[14][data]': 'baronkillspercentage',
            'columns[14][name]': '',
            'columns[14][searchable]': 'true',
            'columns[14][orderable]': 'true',
            'columns[14][search][value]': '',
            'columns[14][search][regex]': 'false',
            'columns[15][data]': 'wardsplacedpermin',
            'columns[15][name]': '',
            'columns[15][searchable]': 'true',
            'columns[15][orderable]': 'true',
            'columns[15][search][value]': '',
            'columns[15][search][regex]': 'false',
            'columns[16][data]': 'wardskilledpermin',
            'columns[16][name]': '',
            'columns[16][searchable]': 'true',
            'columns[16][orderable]': 'true',
            'columns[16][search][value]': '',
            'columns[16][search][regex]': 'false',
            'columns[17][data]': 'wardskilledrate',
            'columns[17][name]': '',
            'columns[17][searchable]': 'true',
            'columns[17][orderable]': 'true',
            'columns[17][search][value]': '',
            'columns[17][search][regex]': 'false',
            'columns[18][data]': 'towertakensPergame',
            'columns[18][name]': '',
            'columns[18][searchable]': 'true',
            'columns[18][orderable]': 'true',
            'columns[18][search][value]': '',
            'columns[18][search][regex]': 'false',
            'columns[19][data]': 'towerdeathsPergame',
            'columns[19][name]': '',
            'columns[19][searchable]': 'true',
            'columns[19][orderable]': 'true',
            'columns[19][search][value]': '',
            'columns[19][search][regex]': 'false',
            'order[0][column]': '2',
            'order[0][dir]': 'desc',
            'start': '0',
            'length': '20',
            'search[value]': '',
            'search[regex]': 'false',
            'area': '',
            # 'eid': '704',
            'type': 'team',
            'gametype': 2,
            'filter': '{"team":{},"player":{},"meta":{}}',
        }
        response = requests.post(url=url, data=data, headers=headers1, timeout=10, verify=False)
        # print response.text
        response_json = response.json()
        # print response_json
        event_list = response_json.get('eventList')
        # print event_list
        # print 'event_list的数据类型：', type(event_list)
        print '一项游戏类别列表下所有赛事的数量：', len(event_list)
        if isinstance(event_list, dict):
            for event in event_list.values():
                name = event.get('name')    # 赛事名称
                print '赛事名称：', name
                eid = event.get('eid')    # 赛事id
                print '赛事id：', eid
                wanplus_data(game_name, type_name, eid, fileout, name)    # 获取每场赛事的内容接口
        elif isinstance(event_list, list):
            for event in event_list:
                name = event.get('name')    # 赛事名称
                print '赛事名称：', name
                eid = event.get('eid')    # 赛事id
                print '赛事id：', eid
                wanplus_data(game_name, type_name, eid, fileout, name)  # 获取每场赛事的内容接口


def wanplus_data(game_name, type_name, eid, fileout, name):
    '''
    获取每场赛事的战队数据、选手数据
    :param game_name: 游戏名称
    :param type_name: 游戏类型
    :param eid: 每场比赛id
    :return:
    '''
    # 每类游戏下的每场赛事eid需要获取两种接口--data
    url = 'https://www.wanplus.com/ajax/stats/list'
    game_type_ls = {
        '2': ['lol_team', 'lol_player'],
        '6': ['wzry_team', 'wzry_player'],
        '1': ['dota_team', 'dota_player'],
        '7': ['qiuqiu_team', 'qiuqiu_player'],
        '8': ['smzh_ol_team', 'smzh_ol_player']
    }    # 游戏类型和每类游戏下的两种接口
    type_dict = {
        'lol_team': lol,
        'lol_player': lol1,
        'wzry_team': wzry,
        'wzry_player': wzry1,
        'dota_team': dota,
        'dota_player': dota1,
        'qiuqiu_team': qiuqiu,
        'qiuqiu_player': qiuqiu,
        'smzh_ol_team': smzh_ol,
        'smzh_ol_player': smzh_ol1,
    }    # 每种接口与每种接口的data的对应关系
    game_type = {
        'lol_team': 'team',
        'lol_player': 'player',
        'wzry_team': 'team',
        'wzry_player': 'player',
        'dota_team': 'team',
        'dota_player': 'player',
        'qiuqiu_team': 'team',
        'qiuqiu_player': 'player',
        'smzh_ol_team': 'team',
        'smzh_ol_player': 'player',
    }     # 每种接口中的data中的type参数对应关系
    gam_a_ls = game_type_ls.get(type_name)    # 获取每种游戏的data
    for game_a in gam_a_ls:
        print '哪种游戏下的哪种接口类型：', game_a
        data_dict = type_dict.get(game_a)
        print '哪种游戏下的data模板：', data_dict
        type1 = game_type.get(game_a)
        print '哪种游戏下的data中的type参数值：', type1
        if type1 == 'team':
            game_data_type = '战队数据'
        elif type1 == 'player':
            game_data_type = '选手数据'
        data_dict.update({'eid': eid, 'gametype': int(type_name), 'type': type1})
        print '更新后的data值：', data_dict

        wanplus_game(url, data_dict, type_name, fileout, game_name, name, game_data_type)    # 赛事数据接口


def wanplus_game(url, data_dict, type_name, fileout, game_name, name, game_data_type):
    '''
    获取每场赛事的赛事数据
    :param url: 每场赛事的战队数据或选手数据的url
    :param data_dict: 请求体
    :param type_name: 游戏类型
    :param fileout: 文件
    :param game_name: 游戏类别
    :param name: 赛事名称
    :param game_data_type:数据类别
    :return: 每场赛事的战队数据或选手数据
    '''
    print 'url：', url
    if type_name in ['2', '6', '1']:
        response = requests.post(url=url, data=data_dict, headers=headers, timeout=10, verify=False)
        # print response.text
        response_json = response.json()
        data = response_json.get('data')
        if data:
            print data
            print '数据长度：', len(data)
            kda = str(data[0].get('kda'))
            print 'kda的值：', kda
            print kda.split('.'), '****', kda.split('.')[-1]
            if len(kda.split('.')[-1]) == 1:
                print 'ok'
                data1 = {'game_name': game_name, 'name': name, 'game_data_type':game_data_type, 'data': data}
                content = json.dumps(data1, ensure_ascii=False)
                fileout.write(content)
                fileout.write('\n')
                fileout.flush()
            else:

                return wanplus_game(url, data_dict, type_name, fileout, game_name, name, game_data_type)
        else:  # data为空
            pass
    elif type_name == '7':
        response = requests.post(url=url, data=data_dict, headers=headers, timeout=10, verify=False)
        # print response.text
        response_json = response.json()
        data = response_json.get('data')
        if data:
            print data
            print '数据长度：', len(data)
            totaldeaths = str(data[0].get('totaldeaths'))
            print 'totaldeaths的值：', totaldeaths
            if '.' not in totaldeaths:
                print 'ok'
                data1 = {'game_name': game_name, 'name': name, 'game_data_type': game_data_type, 'data': data}
                content = json.dumps(data1, ensure_ascii=False)
                fileout.write(content)
                fileout.write('\n')
                fileout.flush()
            else:
                return wanplus_game(url, data_dict, type_name, fileout, game_name, name, game_data_type)

    elif type_name == '8':
        response = requests.post(url=url, data=data_dict, headers=headers, timeout=10, verify=False)
        # print response.text
        response_json = response.json()
        data = response_json.get('data')
        if data:
            print data
            print '数据长度：', len(data)
            deaths = str(data[0].get('deaths'))
            print 'deaths的值：', deaths
            if '.' not in deaths:
                print 'ok'
                data1 = {'game_name': game_name, 'name': name, 'game_data_type': game_data_type, 'data': data}
                content = json.dumps(data1, ensure_ascii=False)
                fileout.write(content)
                fileout.write('\n')
                fileout.flush()
            else:
                return wanplus_game(url, data_dict, type_name, fileout, game_name, name, game_data_type)


def get_cookies():
    '''
    获取cookie以及x-csrf-token
    :return:
    '''
    game_rank_url = 'https://www.wanplus.com/lol/ranking'
    response = get(game_rank_url, headers, 10, '获取cookies和x-csrf-token的url：')
    if response is not None:
        response_cookies = response.cookies
        wanplus_token = response_cookies.get('wanplus_token')    # wanplus_token
        print 'wanplus_token：', wanplus_token
        wanplus_csrf = response_cookies.get('wanplus_csrf')    # wanplus_csrf
        print 'wanplus_csrf：', wanplus_csrf
        cookie = 'wanplus_token={}; wanplus_csrf={}; '.format(wanplus_token, wanplus_csrf) + 'gameType={};'
        print 'cookie：', cookie

        csrf_token = excu_js('getToken', wanplus_token)    # 执行js代码接口
        headers1.update({'cookie': cookie, 'x-csrf-token': csrf_token})
        print 'headers1：', headers1
    else:
        print '获取cookies和x-csrf-token的response is None'


def main():
    print time.strftime('[%Y-%m-%d %H:%M:%S]'), 'start'
    date = time.strftime('%Y%m%d')
    dest_path = '/ftp_samba/112/spider/fanyule_two/wanplus'  # linux上的文件目录
    # dest_path = os.getcwd()    # windows上的文件目录
    if not os.path.exists(dest_path):
        os.makedirs(dest_path)
    dest_file_name = os.path.join(dest_path, 'wanplus_database_' + date)
    tmp_file_name = os.path.join(dest_path, 'wanplus_database_' + date + '.tmp')
    fileout = open(tmp_file_name, 'w')
    get_cookies()  # 获取cookie以及x-csrf-token接口
    wanplus_all_eid(fileout)  # 玩加电竞项目接口
    fileout.flush()
    fileout.close()
    print time.strftime('[%Y-%m-%d %H:%M:%S]'), 'end'
    os.rename(tmp_file_name, dest_file_name)


if __name__ == '__main__':
    main()
    # get_cookies()


